#### Ozmen Emre DEMIRKOL @2019 ####
# Create new network bridge before run this. ("sudo docker network create web")
# Change some lines as pointed out
# Make local firewall settings. (Exp. "firewall-cmd --add-port=8080/tcp --permanent")

logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[entryPoints]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
       ]
      [[entryPoints.https.tls.certificates]]
         certFile = "certs/star_example.cer" # <---- ChangeMe with your wildcard certificate file
         keyFile = "certs/star_example.key" # <----- ChangeMe with your key file

  [entryPoints.traefik]
  address=":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic]
        users = ["admin:$apr1$l2lwMRek$1GbYmPijgBmqezpjusqYz1",] # <--- ChangeMe with result of 'htpasswd -nb username password'

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = false

[ping]
  entryPoint = "traefik"

[retry]

[healthcheck]

[docker]
 endpoint = "unix:///var/run/docker.sock"
 domain = "example.com"
 watch = true
 exposedByDefault = false
 usebindportip = true
 swarmMode = false
 swarmModeRefreshSeconds = 15
 network = "web"
